CREATE SEQUENCE seq_client_id
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE seq_ticket_id
    START WITH 1
    INCREMENT BY 1;
CREATE TABLE client
(
    ID   BIGINT DEFAULT nextval('seq_client_id'),
    NAME VARCHAR(200) NOT NULL CHECK (LENGTH(NAME) >= 3),
    CONSTRAINT pk_client_id PRIMARY KEY (ID)
);

CREATE TABLE planet
(
    ID   VARCHAR CHECK (ID ~ '^[A-Z0-9]+$'),
    NAME VARCHAR(500) NOT NULL CHECK (LENGTH(NAME) >= 1),
    CONSTRAINT pk_planet_id PRIMARY KEY (ID)
);

CREATE TABLE ticket
(
    ID   BIGINT DEFAULT nextval('seq_ticket_id'),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENT_ID   BIGINT NOT NULL,
    FROM_PLANET_ID VARCHAR NOT NULL,
    TO_PLANET_ID VARCHAR NOT NULL,
    CONSTRAINT pk_ticket_id PRIMARY KEY (ID),
    CONSTRAINT fk_client_id FOREIGN KEY (CLIENT_ID) REFERENCES client (ID),
    CONSTRAINT fk_planet_from_id FOREIGN KEY (FROM_PLANET_ID) REFERENCES planet (ID),
    CONSTRAINT fk_planet_to_id FOREIGN KEY (TO_PLANET_ID) REFERENCES planet (ID)
);